export const aboutDaveCutter =
	"I’m Dave, a product designer and front-end developer with 25 years experience in software product development for startup & enterprise clients. I specialise in human-centred design, intuitive UX & UI, and elegant front-end code. I also study the History & Philosophy of Science and International Politics at the University of Melbourne.";

export const portfolio = [
	{
		key: 1,
		client: "Art Processors",
		location: "Melbourne",
		year: 2022,
		title: "Art Processors: Pladia",
		link: "https://www.artprocessors.net/what-we-do/pladia",
		description:
			"I designed Pladia: a professional experience design app for museum and art gallery storytellers and technicians. As visitors explore a venue like a Museum or Art Gallery, they click through details of each artwork or, in' immersive' tours, remain hands-free as experiences are streamed to their device.",
		credit: "Video from Art Processors",
		credit_link: "https://vimeo.com/831709043", // Publically Visible and Downloaded 8 Apr 2024
		color: "#A6784F",
		slides: [
			// {
			//   type: "youtube",
			//   ssrc: "dB_Boky4YPo",
			//   zsrc: "dB_Boky4YPo",
			// },
			{
				key: 1,
				type: "video",
				ssrc: "/portfolio_2021/assets/slides/pladia-video-720.mp4",
				psrc: "/portfolio_2021/assets/slides/pladia-video-poster.png",
			},
		],
	},
	{
		key: 2,
		client: "mod.io",
		location: "Melbourne",
		year: 2021,
		title: "mod.io Marketplace",
		link: "https://mod.io/g",
		description:
			"I redesigned the mod.io marketplace, updating the information architecture, design system, UI, and UX - from the ground up - to be an easier, more compelling, and more community-driven experience for both publishers and gamers - who collaborated on thousands of mods across platforms.",
		color: "#161726",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/modio-app-01.png",
				zsrc: "/portfolio_2021/assets/slides/modio-app-01.png",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/modio-app-02.png",
				zsrc: "/portfolio_2021/assets/slides/modio-app-02.png",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/modio-app-03.png",
				zsrc: "/portfolio_2021/assets/slides/modio-app-03.png",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/modio-app-04.png",
				zsrc: "/portfolio_2021/assets/slides/modio-app-04.png",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/modio-app-05.png",
				zsrc: "/portfolio_2021/assets/slides/modio-app-05.png",
			},
		],
	},
	{
		key: 3,
		client: "mod.io",
		location: "Melbourne",
		year: 2021,
		title: "mod.io Home Page",
		link: "https://mod.io/",
		description:
			"Designing ONE homepage for both gamers and game developers, as well as for desktop, tablet, and mobile, all in one - to serve mod.io's groundbreaking technology in mod development and distribution across gaming platforms!",
		color: "#69B3D7",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/modio-home-01.png",
				zsrc: "/portfolio_2021/assets/slides/modio-home-01-zoom.png",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/modio-home-02.png",
				zsrc: "/portfolio_2021/assets/slides/modio-home-02-zoom.png",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/modio-home-03.png",
				zsrc: "/portfolio_2021/assets/slides/modio-home-03.png",
			},
		],
	},
	{
		key: 4,
		client: "Sports Performance Tracking",
		location: "Melbourne",
		year: 2020,
		title: "Game Traka",
		link: "https://gametraka.com/",
		description:
			"A complete redesign and redevelopment of Sports Performance Tracking's athlete analytics and performance improvement software system, 'Game Traka', utilizing data from GPS and accelerometer tracking devices worn by athletes all over the world and designed for both sports scientists as well as coaches and players to take full advantage of.",
		credit: "Video Produced by Sports Performance Tracking",
		color: "#32383D",
		slides: [
			// {
			//   type: "youtube",
			//   ssrc: "XSvFyyYjfc8",
			//   zsrc: "XSvFyyYjfc8",
			// },
			{
				key: 1,
				type: "video",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-video-720.mp4",
				psrc: "/portfolio_2021/assets/slides/spt-gt4-video-poster.png",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-01.png",
				zsrc: "/portfolio_2021/assets/slides/spt-gt4-01-zoom.png",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-02.png",
				zsrc: "/portfolio_2021/assets/slides/spt-gt4-02-zoom.png",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-03.png",
				zsrc: "/portfolio_2021/assets/slides/spt-gt4-03-zoom.png",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-04.png",
				zsrc: "/portfolio_2021/assets/slides/spt-gt4-04-zoom.png",
			},
			{
				key: 6,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-05.png",
				zsrc: "/portfolio_2021/assets/slides/spt-gt4-05-zoom.png",
			},
			{
				key: 7,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-06.png",
				zsrc: "/portfolio_2021/assets/slides/spt-gt4-06-zoom.png",
			},
			{
				key: 8,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-07.png",
				zsrc: "/portfolio_2021/assets/slides/spt-gt4-07-zoom.png",
			},
			{
				key: 9,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-gt4-08.png",
				zsrc: "/portfolio_2021/assets/slides/spt-gt4-08-zoom.png",
			},
		],
	},
	{
		key: 5,
		client: "Sports Performance Tracking",
		location: "Melbourne",
		year: 2019,
		title: "SPT Bridge",
		description:
			"SPT's Bridge app connects SPT devices to the Game Traka platform. After every game and practice coaches and players upload athletic data to well-tagged events for analysis.",
		color: "#CCB100", // FFDD00 too bright
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-01.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-01.png",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-02.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-02.png",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-03.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-03.png",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-04.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-04.png",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-05.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-05.png",
			},
			{
				key: 6,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-06.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-06.png",
			},
			{
				key: 7,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-07.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-07.png",
			},
			{
				key: 8,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-08.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-08.png",
			},
			{
				key: 9,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/spt-bridge-09.png",
				zsrc: "/portfolio_2021/assets/slides/spt-bridge-09.png",
			},
		],
	},
	{
		key: 6,
		client: "ESPN / Disney",
		location: "Melbourne",
		year: 2018,
		title: "ESPN FootyTips App",
		link: "https://www.footytips.com.au/",
		description:
			"After the completely redesigned ESPN Footytips App was released, I designed sucessful iterations and new features, creating fresh experiences for Australia's biggest tipping app!,",
		color: "#284A85",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-app-05-06.png",
				zsrc: "/portfolio_2021/assets/slides/espn-app-05-06.png",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-app-01-02.png",
				zsrc: "/portfolio_2021/assets/slides/espn-app-01-02.png",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-app-03-04.png",
				zsrc: "/portfolio_2021/assets/slides/espn-app-03-04.png",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-app-07-08.png",
				zsrc: "/portfolio_2021/assets/slides/espn-app-07-08.png",
			},
		],
	},
	{
		key: 7,
		client: "ESPN / Disney",
		location: "Melbourne",
		year: 2017,
		title: "ESPN Games",
		description:
			"At ESPN I designed and developed a number of new games across a variety of sports and alongside a wide range of coporate partners.",
		color: "#BB261A",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-games-01-02.png",
				zsrc: "/portfolio_2021/assets/slides/espn-games-01-02.png",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-games-03-04.png",
				zsrc: "/portfolio_2021/assets/slides/espn-games-03-04.png",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-games-05.png",
				zsrc: "/portfolio_2021/assets/slides/espn-games-05.png",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-games-06.png",
				zsrc: "/portfolio_2021/assets/slides/espn-games-06.png",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-games-07.png",
				zsrc: "/portfolio_2021/assets/slides/espn-games-07.png",
			},
			{
				key: 6,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/espn-games-08.png",
				zsrc: "/portfolio_2021/assets/slides/espn-games-08.png",
			},
		],
	},
	{
		key: 8,
		client: "Yahoo! Sports",
		location: "Los Angeles",
		year: 2014,
		title: "Yahoo! Rivals App",
		description:
			"This project entirely redesigned the existing rivals website into a fully responsive mobile app by reworking the view layer and leaving the BE entirely alone: FE Surgery!",
		color: "#0A4EA3",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/rivals-mobile-01.png",
				zsrc: "/portfolio_2021/assets/slides/rivals-mobile-01.png",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/rivals-mobile-02.png",
				zsrc: "/portfolio_2021/assets/slides/rivals-mobile-02.png",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/rivals-mobile-03.png",
				zsrc: "/portfolio_2021/assets/slides/rivals-mobile-03.png",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/rivals-mobile-04.png",
				zsrc: "/portfolio_2021/assets/slides/rivals-mobile-04.png",
			},
		],
	},
	{
		key: 9,
		client: "Meteor Games",
		location: "Los Angeles",
		year: 2010,
		title: "Game UI Designs",
		description:
			"While at Meteor Games I wore many hats: graphic designer, FE developer, IT manager... and loved every minute of it, including helping to bring these games to life!",
		color: "#333",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-03.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-03.png",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-02.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-02.png",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-01.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-01.png",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-04.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-04.png",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-05.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-05.png",
			},
			{
				key: 6,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-06.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-06.png",
			},
			{
				key: 7,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-07.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-07.png",
			},
			{
				key: 8,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-08.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-08.png",
			},
			{
				key: 9,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-09.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-09.png",
			},
			{
				key: 10,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-10.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-10.png",
			},
			{
				key: 11,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-11.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-11.png",
			},
			{
				key: 12,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/meteor-games-12.png",
				zsrc: "/portfolio_2021/assets/slides/meteor-games-12.png",
			},
		],
	},
];

export const photography = [
	{
		key: 1,
		client: "Luna Flip Jewellery",
		location: "Melbourne",
		year: 2021,
		title: "Luna's 2021 Collection",
		description:
			"A photoshoot of the whole spring inventory, shot on a sunny afternoon in a Brighton back garden.",
		color: "#3A413D",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-01.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-01.jpg",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-02.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-02.jpg",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-03.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-03.jpg",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-04.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-04.jpg",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-05.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-05.jpg",
			},
			{
				key: 6,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-06.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-06.jpg",
			},
			{
				key: 7,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-07.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-07.jpg",
			},
			{
				key: 8,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-08.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-08.jpg",
			},
			{
				key: 9,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-09.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-09.jpg",
			},
			{
				key: 10,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-10.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-10.jpg",
			},
			{
				key: 11,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-11.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-11.jpg",
			},
			{
				key: 12,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-12.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-12.jpg",
			},
			{
				key: 13,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-13.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-13.jpg",
			},
			{
				key: 14,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-14.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-14.jpg",
			},
			{
				key: 15,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-15.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-15.jpg",
			},
			{
				key: 16,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-16.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-16.jpg",
			},
			{
				key: 17,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-17.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-17.jpg",
			},
			{
				key: 18,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/farah-jewellery-18.jpg",
				zsrc: "/portfolio_2021/assets/slides/farah-jewellery-18.jpg",
			},
		],
	},
	{
		key: 2,
		client: "Eric S",
		location: "Melbourne",
		year: 2019,
		title: "Eric's Gold",
		description:
			"Experimenting with super-micro work on real gold found in the wilds of Victoria, all at sub millimeter scales! Don't. Breathe.",
		color: "#272829",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/eric-gold-01.jpg",
				zsrc: "/portfolio_2021/assets/slides/eric-gold-01.jpg",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/eric-gold-02.jpg",
				zsrc: "/portfolio_2021/assets/slides/eric-gold-02.jpg",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/eric-gold-03.jpg",
				zsrc: "/portfolio_2021/assets/slides/eric-gold-03.jpg",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/eric-gold-04.jpg",
				zsrc: "/portfolio_2021/assets/slides/eric-gold-04.jpg",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/eric-gold-05.jpg",
				zsrc: "/portfolio_2021/assets/slides/eric-gold-05.jpg",
			},
		],
	},
	{
		key: 3,
		client: "Caroline Patisserie",
		location: "Melbourne",
		year: 2017,
		title: "Grand-Opening Product Photos",
		description:
			"This could have been a professional photoshoot, real classy, a great set for a charming client, and I managed to collaborate with Hanna at Hang Studios! But there was too much chocolate, too much flavor, too much, did I say chocolate?",
		color: "#8E1A11",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-03.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-03.jpg",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-02.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-02.jpg",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-01.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-01.jpg",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-04.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-04.jpg",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-05.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-05.jpg",
			},
			{
				key: 6,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-06.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-06.jpg",
			},
			{
				key: 7,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-07.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-07.jpg",
			},
			{
				key: 8,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-08.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-08.jpg",
			},
			{
				key: 9,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-09.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-09.jpg",
			},
			{
				key: 10,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/caroline-patisserie-10.jpg",
				zsrc: "/portfolio_2021/assets/slides/caroline-patisserie-10.jpg",
			},
		],
	},
	{
		key: 4,
		client: "Dave Cutter",
		location: "Melbourne & Los Angeles",
		year: 2019,
		title: "'Keepers'",
		description:
			"In 2019 I picked up a new camera, and these shots document some of the fun I've had with it over these last few years.",
		color: "#615350",
		slides: [
			{
				key: 1,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-14.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-14.jpg",
			},
			{
				key: 2,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-02.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-02.jpg",
			},
			{
				key: 3,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-03.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-03.jpg",
			},
			{
				key: 4,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-04.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-04.jpg",
			},
			{
				key: 5,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-05.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-05.jpg",
			},
			{
				key: 6,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-06.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-06.jpg",
			},
			{
				key: 7,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-07.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-07.jpg",
			},
			{
				key: 8,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-08.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-08.jpg",
			},
			{
				key: 9,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-09.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-09.jpg",
			},
			{
				key: 10,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-10.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-10.jpg",
			},
			{
				key: 11,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-11.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-11.jpg",
			},
			{
				key: 12,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-12.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-12.jpg",
			},
			{
				key: 13,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-13.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-13.jpg",
			},
			{
				key: 14,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-01.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-01.jpg",
			},
			{
				key: 15,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-15.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-15.jpg",
			},
			{
				key: 16,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-16.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-16.jpg",
			},
			{
				key: 17,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-17.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-17.jpg",
			},
			{
				key: 18,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-18.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-18.jpg",
			},
			{
				key: 19,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-19.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-19.jpg",
			},
			{
				key: 20,
				type: "image",
				ssrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-20.jpg",
				zsrc: "/portfolio_2021/assets/slides/nikon-life-2019-2020-20.jpg",
			},
		],
	},
];
